### ISSUE TITLE
Complain about Block Wallet 2.0 Here!

### ISSUE THREAD

**Issue by cybertim** [cybertim/blockwallet#34]
Block Wallet 2.0 has been released and is now live on iOS and Android.

For this update the Private Key needs to be moved from the old Database Scheme to a new one with multi-wallet support. If you used a custom pincode you will need to enter this on App start. Without this code the Private Key cannot be moved into the new Scheme.

If you have any issue regarding the migration like: **my private key is suddenly gone?? help!**
Do **not** remove or reinstall the App. The old database scheme is still (encrypted) preserved. With an update this can be made undone. Just report your issue here and I will take a look.

Other bugs or issues can be placed here as well. But most *old* bugs should be gone now, like paste / manual input and gas amount / limit settings.

Happy complaining ;-)

**Comment by DJS600** [comment]
Just downloaded the app, deposited currency, now to withdraw its coming up with key pad but I have not ever setup a pin? Please help

**Comment by cybertim** [comment]
This is probably still Blockwallet 1.0 you are referring to, but to answer your question, the default pincode is 0000 (it was mentioned in the intro screen and listed in the internal help a few times). In blockwallet 2.0 the pincode has been omitted.

**Comment by toty10** [comment]
How can I recover my passcode?

**Comment by cybertim** [comment]
If you - for some reason - forgot the passcode you can do the following:
- guess till you got it right
- recover the wallet with the backup you made, this will reset the passcode back to 0000

**Comment by LasloMorpheen** [comment]
Hi. I’ve had the wallet a while now. Tried to send Ether today and when the number key pad comes up, I type in my amount to send nothing happens.

**Comment by cybertim** [comment]
@LasloMorphine could you check the issue #37 and see if this is the same problem? (Maybe also an iPad Air?)

**Comment by LasloMorpheen** [comment]
Sounds like same thing. I’m using iPad Pro. Not working in landscape or portrait.

**Comment by FrankyJB** [comment]
I have same problem with iPad Pro when trying to send ether on new interface.
All ok till number pad comes up when you try to tap in the amount nothing shows and nothing happens. Any answers to this issue yet?
Thanks

**Comment by cybertim** [comment]
Yes, in the Beta (only available on Android tho) the Send keypad has been replaced with a more compatible solution and the 'accept' button has been moved on the bottom.
The iOS update will be pushed a.s.a.p. (maybe tonight), but the review process always takes some time (one or two days..)

Here is an example of what it is going to look like on the iPad:
![simulator screen shot - ipad pro 10 5-inch - 2018-01-15 at 17 37 54](https://user-images.githubusercontent.com/5379564/34952746-103719dc-fa1b-11e7-881e-a1dd368a3a3d.png)

**Comment by cybertim** [comment]
iOS update to version 2.0.4 is delayed since it was rejected today (something about a screenshot..) so it will take a bit more time.

**Comment by Tallen58** [comment]
Updated app on ipad pro. Dont know passcode and 0000 doesnt work. How do I recover?

**Comment by cybertim** [comment]
Like mentioned before, the default code is 0000 (and when the App does the internal update is tried automatically). When prompted for a passcode during the update it means you must have changed the default pin/passcode to a different code.

The only solution is trying to remember the code..

Another solution is available if you have the Private Key (Paper Wallet Backup) or wrote the Recovery Phrase down somewhere. In that case you can safely remove the App from the device and install it again from the store. When reinstalled you can restore the Wallet and the passcode will be omitted.

**Comment by FrankyJB** [comment]
Still not able to access my funds on iPad this is getting ridiculous just want my funds and dump this wallet

**Comment by cybertim** [comment]
It has been fixed for several days now.

But I cannot control the "ridiculous" review process of the App Store. Only Apple can fix this for you. The update was send to Apple 2 days ago, and it is in review so it could be published yesterday, right now or next week...

Also, you can export the Private Key and use for instance MyEtherWallet.com to transfer funds around, no need to wait for the update anyways.

**Comment by FrankyJB** [comment]
I will have to try exporting the key then as there is still no solution to send from the Blockwallet.
Thanks

**Comment by cybertim** [comment]
Believe it or not, the 2.0.4 update has been approved a few minutes ago.
Though it could take a few hours before you can actually see the update in the App Store.

I kid you not, one of the questions why it was postphoned: "Which cryptocurrencies can your app use?"

**Comment by FrankyJB** [comment]
It was finally rectified and is once again functioning. Two smaller issues I have, I seem to have duplicated my Golem balance and am worried that if I delete one it will delete both and I will have no trace of the Golem in the wallet and my Tron balance shows number of a Tron but no $value under the crypto entry. Any help always appreciated.

**Comment by cybertim** [comment]
If you see a Token two times on the overview it is safe to just remove one of them in the Token Management. The Token Management does not alert the tokens in any way on the ether address.

But if you added a Wallet two times, make sure to Backup first before trying to remove one in the Wallet Management. This is a process which cannot be undone without a backup.
Though it does not alter any value on the address (it is all stored in the blockchain), you can lose your access to the blockchain. But with a Wallet Backup you are always safe.

And with Tron, do you mean TRX? If so, did you add it through the 'Popular List'? Or manually entered the values in the Token Management?

**Comment by FrankyJB** [comment]
Hi

I removed one and it removed both so does that mean that my Tron is gone there should be a record on My Ether Scan shouldn't there? Is it possible for me to resend it to the wallet from there. I have backed this wallet up just 24 hours ago.

FrankyJB

________________________________

**Comment by cybertim** [comment]
When removing, there should have been a 'warning' about the token not being removed from the address, only from the overview.
So just add the Token back to the Overview (in the Token Management screen) and it should only show once after that.

**Comment by FrankyJB** [comment]
sorry

I AM TALKING TWO ISSUES HERE AND CONFUSING YOU AND MYSELF.

I removed one of the Golem entries and both disappeared from the overview but I have backed up prior just 24 hours ago, The Golem has been in the wallet for a month so I should be able to recover this Golem? Can I find the transaction on My Ether Scan and recover it from there or what do I need to do.


Separate Issue - The Tronix shows no value just number of tokens. I have found the transaction on etherscan.io which shows I sent it direct from Binance Exchange in two transfers one of 70 and one of 40,145 tokens. Shows the token value $2962.65, value per token $0.0738 @ 0.000070ETH shows token holder address, Contract Address as well as Token transfer or read the smart contract. Shows TX Hash, Age From IN To Quantity (in the two transactions). It appears I did everything correct but I am sure I did not enter it into the wallet from popular tokens list, I am sure when I did the transaction it just appeared in the wallet under the ethereum address. In the wallet it shows no transaction date like my Ether, ANT and GNT which has disappeared as per issue1 above, just says 22/1/2018 then when you open up Tronix in the wallet it states from Invalid Date until Now.

FrankyJB

________________________________

**Comment by FrankyJB** [comment]
Hi Tim

That worked on the Golem, just a single entry and correct amount, now just need to sort the Tronix.

FrankyJB

________________________________

**Comment by cybertim** [comment]
To solve the Tronix issue, it is important the Symbol is correctly entered in the Token Management. It should be (according to https://etherscan.io/token/Tronix) **TRX**.
If this isn't set correctly the Fiat value can not be showed because the Data is received from https://www.cryptocompare.com/coins/trx/overview using the keyword 'trx'.
Is this the case? Does it show as 'TRX' ? If not, you can just remove it and add it again (from the popular list) in the Token Managent just like Golem.

**Comment by FrankyJB** [comment]
[Image]
Tim
Yes it’s entered correctly as TRX in the Wallet overview and TRX in the Token manager, displays TRX amount but no fiat value. When I click to follow it back to etherscan.io from the token manager there is no transaction showing but the transaction is clearly displayed when you follow it from the binance send transaction to the wallet.[Image] [Image]


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FrankyJB** [comment]
Hi Tim we discussed a couple of issues recently and I was able to rectify one problem with your help.
But I still have this ongoing issue with my TRX Tronix balance only showing the number of coins in the wallet but no fiat value. I have several other erc20tokens in the wallet but only have a problem with the TRX. When I transferred these tokens from binance  am sure I did not go to the popular coin list instead just entered the ether address and sent. The transaction is viewable in my ether scan and the tokens are in my wallet they just don’t show the fiat value. I was just going to try and send a small,amount to another wallet and see how they show up in that wallet. Any other suggestions?

**Comment by hooka123** [comment]
Why is my wallet constantly slow loading.constant network/connection problem .not my network no problem with other wallets only block wallet

**Comment by hooka123** [comment]
25 min still not loaded ? Been on other wallets no problem!!

**Comment by cybertim** [comment]
blockwallet uses infura as the default (free) blockchain server, maybe they had an issue this night, status can always be checked here: https://infura.io/status
if this is not stable enough you can always host your own geth-server and link it to your blockwallet app.

**Comment by jumanjikan** [comment]
I tried sending some erc20 tokens to my friends address. But the transactions never work. What is the process? I put high gas and gwei. How do I send erc20 from block wallet to myetherwallet?

**Comment by cybertim** [comment]
@jumanjikan 
Incoming token transactions do not 'show' in the list, but you should be able to see the totals increase on the target wallet if the token was added with the tracker to the overview.

If you export your private key you can import it into myetherwallet and try to send the token with their interface.  Myetherwallet does also keep a big database themselves which is able to even match and show incoming token-transactions on the public addresses.

**Comment by koinmaker** [comment]
Block Wallet server is off line, someone have news?

**Comment by cybertim** [comment]
Hosting service provider issue. They are working in it, don't have an est 
yet. You can always use you own hosted geth service or export you wallet 
and choose a different service in the meantime.

**Comment by cybertim** [comment]
The service has been fixed. And to top it off the SSL certs had to be refreshed as well, but all is done and you can use the free blockwallet.eu geth service once again! Thanks for the patience.

**Comment by cybertim** [comment]
#54

**Comment by FrankyJB** [comment]
Hi Tim
Mate I dont know why you emailed me I haven’t logged into Github since my coin was, I thought, stuck in your wallet due to your credit card provider giving you a hassle about a payment and blocked the server or something like that. But that was months & months ago so whadup?
I still have and use my blockwallet, it still refuses to show a fiat balance on some tokens; DataExchange token comes to mind, but when I transfer them around its all fine, shows token volume but not $ value until it hits another destination wallet. Tell me does that wallet ever need upgrades or is that automatically done, cause i dont remember ever seeing any update messages.
Thanks
Frank

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
